---
abstract: "Perl interface to functions that assist in working\r\nwith salted hashes.\r"
author:
  - 'Sascha Kiefer, L<esskar@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-SaltedHash
requires:
  Digest: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Crypt-SaltedHash
  repository: git://github.com/campus-explorer/crypt-saltedhash.git
version: 0.08
